/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type QueryRejected = {
    status?: QueryRejected.status;
};
export namespace QueryRejected {
    export enum status {
        WORKFLOW_EXECUTION_STATUS_UNSPECIFIED = 'WORKFLOW_EXECUTION_STATUS_UNSPECIFIED',
        WORKFLOW_EXECUTION_STATUS_RUNNING = 'WORKFLOW_EXECUTION_STATUS_RUNNING',
        WORKFLOW_EXECUTION_STATUS_COMPLETED = 'WORKFLOW_EXECUTION_STATUS_COMPLETED',
        WORKFLOW_EXECUTION_STATUS_FAILED = 'WORKFLOW_EXECUTION_STATUS_FAILED',
        WORKFLOW_EXECUTION_STATUS_CANCELED = 'WORKFLOW_EXECUTION_STATUS_CANCELED',
        WORKFLOW_EXECUTION_STATUS_TERMINATED = 'WORKFLOW_EXECUTION_STATUS_TERMINATED',
        WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW = 'WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW',
        WORKFLOW_EXECUTION_STATUS_TIMED_OUT = 'WORKFLOW_EXECUTION_STATUS_TIMED_OUT',
    }
}

